# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install build dependencies
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy package and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts --production=false

# Copy source code
COPY src ./src

# Build
RUN npm run build

# Remove dev dependencies and cleanup build tools
RUN npm prune --production && apk del python3 make g++

# Set workdir and default command
WORKDIR /app
CMD ["node", "dist/index.js"]
